# Generated by Zero
# import types as per needed, not all imports are shown here
from msgspec import Struct

from zero import ZeroClient

zero_client = ZeroClient("localhost", 5559, default_timeout=600_000)


class SearchConfig(Struct):
    target: str
    preset: str = "default"
    preference: str = "balance"
    kwargs: dict = {}


class Result(Struct):
    title: str
    content: list[dict[str, str]]


class RpcClient:
    def __init__(self, _zero_client: ZeroClient):
        self._zero_client = _zero_client

    async def echo(self, msg: str) -> str:
        return self._zero_client.call("echo", msg)

    async def fetch(self, url: str) -> Result:
        return self._zero_client.call("fetch", url)

    async def search(self, config: SearchConfig) -> Result:
        return self._zero_client.call("search", config)

    async def list_available_engines(self) -> dict[str, str]:
        return self._zero_client.call("list_available_engines", None)
